# Generated by Django 5.2.7 on 2025-10-29 17:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxwags', '0002_alter_dogpost_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogpost',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
